apiVersion: apps/v1
kind: Deployment
metadata:
  name: cifar-app
spec:
  selector:
    matchLabels:
      app: cifar-app
  replicas: 3
  template:
    metadata:
      labels:
        app: cifar-app
    spec:
      containers:
      - name: cifar-app
        image: kubermatic00/kubermatic-dl:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cifar-app
  labels:
    app: cifar-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: cifar-app