apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-app
spec:
  selector:
    matchLabels:
      run: mnist-app
  replicas: 1
  template:
    metadata:
      labels:
        run: mnist-app
    spec:
      containers:
      - name: mnist-app
        image: julianvega/mnist-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-app
  labels:
    run: mnist-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    run: mnist-app